services:
  - type: web
    name: cyber-incident-resolution-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeploy: true

    envVars:
      - key: SPARK_DRIVER_MEMORY
        value: 512m

      - key: SPARK_LOCAL_IP
        value: 127.0.0.1

      - key: SPARK_LOCAL_HOSTNAME
        value: localhost

      - key: PYSPARK_PYTHON
        value: python3